# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:59:39+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, constr


class Status(Enum):
    emailNotFound = 'emailNotFound'
    emailNotVerified = 'emailNotVerified'
    created = 'created'


class Field200OK(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    dkimKeys: Optional[List] = None
    status: Status


class Status1(Enum):
    integer_401 = 401


class Title(Enum):
    Unauthorized = 'Unauthorized'


class Type(Enum):
    https___tools_ietf_org_html_rfc7235_section_3_1 = (
        'https://tools.ietf.org/html/rfc7235#section-3.1'
    )


class Field401Unauthorized(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    status: Status1
    title: Title
    traceId: constr(pattern=r'^00-[0-9a-f]{32}-[0-9a-f]{16}-00$')
    type: Type
